43
BigBearBalls/barber-shop-project pull request #47
Opened 2024-11-13 07:16 UTC by Danyssymo

2024-11-13 07:38 UTC, YevganyTyurin commented on calendar-service/src/main/java/eu/senla/calendarservice/dto/IsHolidayDayResponse.java
> +}
Стоит ли делать дто чтобы оборачивать один Boolean?

2024-11-13 08:28 UTC, YevganyTyurin commented on calendar-service/src/main/java/eu/senla/calendarservice/dto/IsHolidayDayResponse.java
> +}
IsHoliday будет корректнее чем IsHolidayDay

2024-11-13 08:36 UTC, YevganyTyurin commented on calendar-service/src/main/java/eu/senla/calendarservice/entity/CalendarDayOff.java
> +}
Слово Calendar излишне, просто DayOff, и в column тоже

2024-11-13 08:42 UTC, YevganyTyurin commented on calendar-service/src/main/java/eu/senla/calendarservice/service/CalendarService.java
> +}
Метод isWorkingDay отдает IsHolidayDayResponse
По логике isWorkingDay должно отдавать IsWorkingDayResponse, либо IsHolidayDay отдавать IsHolidayDayResponse

2024-11-13 09:10 UTC, ChelovechekAD requested changes

2024-11-13 09:10 UTC, ChelovechekAD commented on build.gradle
> +Set<Project> kafkaProjects = Set.of(NOTIFICATION_SERVICE, BOOKING_SERVICE, CALENDAR_SERVICE)
тебе тут кафка  нужна?

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/CalendarController.java
> +@RequestMapping("/calendar/")
api/v1/calendar/
мы же апи пишем, а не урлы на фронте

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/CalendarController.java
> +    @DeleteMapping("working-day/{day}")
DeleteMapping? Может ты хотел написать PostMapping?

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/handler/CalendarExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorResponseBuilder(HttpStatus.BAD_REQUEST, ErrorConstants.MISMATCH_EXCEPTION_ERROR_MESSAGE ,ErrorConstants.MISMATCH_EXCEPTION_ERROR_COD
Форматирование?

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/handler/CalendarExceptionHandler.java
> +                .status(status)
убери  впринципе http статус из ошибки, у тебя этот статус проставляется на самом респонсе, зачем даблить тогда

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/handler/CalendarExceptionHandler.java
Сделай абстрактную ошибку аля ApiException и засунь туда поля типов HttpStatus и ErrorCode, можешь чекнуть пример в моем пул реквесте. И тогда тебе не нужно будет писать под каждую хэндл, а просто через ApiException хэндлить и статус респонса брать из ошибки, а также и еррор код из ошибки, след-но в билдер ты можешь передавать просто ошибку и uri. И в нем уже из ошибки все тянуть

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/dto/ErrorResponse.java
> +    private HttpStatus status;
ненужное поле

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/dto/ErrorResponse.java
> +    private String errorCode;
А, у тебя тут оно вообще стрингой, предлагаю сделать enum для еррор кодов

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/dto/IsHolidayDayResponse.java
> +}
> Стоит ли делать дто чтобы оборачивать один Boolean?

Тут соглашусь, сам запрос подразумевает в ответе только true либо false без каких либо доп полей в последующем

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/mapper/CalendarMapper.java
> +
лишний отступ

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/mapper/CalendarMapper.java
> +
точнее строка

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/service/impl/CalendarServiceImpl.java
> +    public void setWorkingDay(LocalDate day) {
ох, теперь понял почему там DeleteMapping, название метода вводит в ступор, назови его аля deleteDayOff or cancelDayOff

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/service/impl/CalendarServiceImpl.java
> +        }
Меня напрягают такие конструкции
        
     `if(!calendarRepository.existsByDate(day)){
            throw new EmptyDateException("This day is already a working day");
       }
       calendarRepository.deleteByDate(day);`

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/service/impl/CalendarServiceImpl.java
> +        }
"This day is already a working day" почему не в константах

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/util/constants/ErrorConstants.java
> +public class ErrorConstants {
вот это все красиво заменяется енамом

2024-11-13 09:10 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/service/impl/CalendarServiceImpl.java
> +         return calendarMapper.toIsHolidayDayResponse(calendarRepository.existsByDate(day));
Всмысле?
if exist -> isHoliday 
mapTo IsHolidayResponse
но название метода isWorkingDay?
В случае если это выходной, то вернется true, а судя по названию метода получаем, что это рабочий день

2024-11-13 12:19 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/dto/IsHolidayDayResponse.java
> +}
Сегодня возвращаем одно значение, а завтра 2,3,4. Да и в принципе мы же во всем проекте между сервисами бросаемся ДТОшками. Чем календарь сервис хуже ? Зачем ломать это единобразие ?

2024-11-13 12:23 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/service/CalendarService.java
> +}
Тут согл

2024-11-13 12:24 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/entity/CalendarDayOff.java
> +}
В БД у нас уже у всех сервисов идет такое единобразие.
А про класс согл.

2024-11-13 12:27 UTC, Danyssymo commented on build.gradle
> +Set<Project> kafkaProjects = Set.of(NOTIFICATION_SERVICE, BOOKING_SERVICE, CALENDAR_SERVICE)
Да. По идее календарь будет отправлять асинхронные сообщения юзерам и предстоящих выходных.
Или если будем реализовывать перенос броней если в этот день барбер по каким либо причинам будет закрыт, то тоже надо будет отправлять сообщения юзерам

2024-11-13 12:29 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/CalendarController.java
> +@RequestMapping("/calendar/")
Ок. Тогда в букинге надо так же сделать. Там сейчас не так

2024-11-13 12:31 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/CalendarController.java
> +    @DeleteMapping("working-day/{day}")
Тут все верно прописано.
Тут идет логика в том, что я храню в БД выходные дни.
И Удаление подразумевает, что день удаляется из таблицы "Выходные дни" , тем самым становится рабочим

2024-11-13 12:31 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/handler/CalendarExceptionHandler.java
> +    return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(errorResponseBuilder(HttpStatus.BAD_REQUEST, ErrorConstants.MISMATCH_EXCEPTION_ERROR_MESSAGE ,ErrorConstants.MISMATCH_EXCEPTION_ERROR_COD
Тут согл. Исправляю

2024-11-13 12:34 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/controller/handler/CalendarExceptionHandler.java
> +                .status(status)
Тут уже дело вкуса. 
Эти статусы - это конкретика респонс статусов. Типо не просто 400, а 400001, 400002 и.т.д.
Где в дальнейшем можно понять из-за чего конкретно такой статус

2024-11-13 12:35 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/mapper/CalendarMapper.java
> +
Тут согл. Исправлю форматирование по сервису

2024-11-13 12:35 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/service/impl/CalendarServiceImpl.java
> +    public void setWorkingDay(LocalDate day) {
Тут согл. Исправлю

2024-11-13 12:40 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/service/impl/CalendarServiceImpl.java
> +        }
Сделал константы

2024-11-13 12:41 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/util/constants/ErrorConstants.java
> +public class ErrorConstants {
Вкусовщина. Я сделал так

2024-11-13 12:43 UTC, Danyssymo commented on calendar-service/src/main/java/eu/senla/calendarservice/service/impl/CalendarServiceImpl.java
> +         return calendarMapper.toIsHolidayDayResponse(calendarRepository.existsByDate(day));
Это тоже было исправлено.

2024-11-13 16:04 UTC, ChelovechekAD submitted a review, later dismissed

2024-11-13 16:04 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/mapper/CalendarMapper.java
> +
оно же так и осталось

2024-11-13 16:04 UTC, ChelovechekAD commented on calendar-service/src/main/java/eu/senla/calendarservice/service/impl/CalendarServiceImpl.java
> +    public void setWorkingDay(LocalDate day) {
Жду испралвения

2024-11-14 09:10 UTC, ChelovechekAD approved these changes

2024-11-14 09:12 UTC, merged