init catalog service. add basic dependencies
BigBearBalls/barber-shop-project pull request #6
Opened 2024-10-28 13:58 UTC by YevganyTyurin

2024-10-30 16:11 UTC, ChelovechekAD requested changes

2024-10-30 16:11 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/service/impl/MasterServiceImpl.java
> +        if(master.isEmpty()) {
Используешь метод .orElseThrow() у объекта Optional<>
Не нужно писать вот такие конструкцыи с ифом

2024-10-30 16:11 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/service/impl/ProcedureServiceImpl.java
> +            throw new ProcedureExistException(excistProcedure.getId(), ExceptionInfo.NAME_EXIST);
Зачем ты делаешь existByName(), а потом тянешь сущность из бд? Ты делаешь лишний запрос к бд. Во-первых зачем тебе ее айди? Просто выкинь ошибку. Во-вторых, если тебе и нужен этот айди, то просто получай через findByName() объект и смотри, если он есть, то возвращай ошибку с его айди

2024-10-30 16:11 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/service/impl/ProcedureServiceImpl.java
> +        if(procedure.isEmpty()) {
используешь метод .orElseThrow()
Не нужно писать вот такие конструкцыи с ифом

2024-10-30 16:11 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/service/impl/ProcedureServiceImpl.java
Где транзакции вообще?

2024-10-30 16:11 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/service/impl/ProcedureServiceImpl.java
> +        return procedureRepository.save(currantProcedure);
Транзакции! И в случае транзакции, у тебя объект Procedure будет находиться в состоянии персистентности и сохранять его повторно не надо

2024-10-30 16:13 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/controller/aspect/ResponseException.java
> +public record ResponseException(String errorMessage,
не зацепил 4 строку, речь про нее

2024-10-31 14:36 UTC, Viachaslavtsarenkov approved these changes

2024-10-31 15:23 UTC, ChelovechekAD requested changes

2024-10-31 15:23 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/service/impl/ProcedureServiceImpl.java
> +        if(excistProcedure != null) {
Ошибка в слове

2024-10-31 15:23 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/controller/aspect/CustomExceptionHandler.java
> +public class CustomExceptionHandler extends ResponseEntityExceptionHandler {
ситуация не поменялась

2024-10-31 15:46 UTC, ChelovechekAD requested changes

2024-10-31 15:46 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/service/impl/ProcedureServiceImpl.java
> +        Procedure currantProcedure = procedureMapper.toProcedure(getProcedure(procedureId));
Так... Сначало в методе выше мы мапим сущность в дто, а тут мы это дто мапим обратно в сущность, у меня возникает соотв вопрос 
Зачем?

2024-10-31 15:46 UTC, ChelovechekAD commented on catalog/src/main/java/eu/senla/catalog/service/impl/ProcedureServiceImpl.java
> +        return procedureMapper.toProcedureDto(procedureRepository.save(currantProcedure));
Персистентный объект, повторного явного сохранения не требует

2024-11-01 07:30 UTC, Viachaslavtsarenkov commented on catalog/src/main/java/eu/senla/catalog/exception/EntityExistException.java
> +public class EntityExistException extends AbstractException{
Rename class

2024-11-01 07:32 UTC, ChelovechekAD requested changes

2024-11-01 07:54 UTC, Danyssymo commented on catalog/src/main/java/eu/senla/catalog/controller/ProcedureController.java
> +    public ProcedureDto addProcedure(@Valid @RequestBody ProcedureDto procedureDto) {
Тут validated не нужен

2024-11-04 10:48 UTC, closed without merging